version: '3.4'
services:
  database:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
  imagineapps-backend:
    image: imagineapps-backend-image
    build: .
    container_name: imagineapps-backend
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
volumes:
  db-data:
